# Generated by Django 2.0 on 2017-12-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator_name', models.CharField(max_length=100)),
                ('donator_email', models.EmailField(max_length=100)),
                ('donation_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
    ]
