# Generated by Django 2.0 on 2017-12-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('crv', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Veterinary',
                'verbose_name_plural': 'Veterinaries',
            },
        ),
    ]
